// Code generated by MockGen. DO NOT EDIT.
// Source: ./mailer.go
//
// Generated by this command:
//
//	mockgen -source=./mailer.go -destination=./mocks/mailer.go -package=mock -mock_names=Mailer=MockMailer
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	mailer "github.com/jorgeAM/grpc-kata-payment-service/pkg/mailer"
	gomock "go.uber.org/mock/gomock"
)

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
	isgomock struct{}
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockMailer) Send(ctx context.Context, payload *mailer.MailerPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMailerMockRecorder) Send(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMailer)(nil).Send), ctx, payload)
}
